// SPDX-License-Identifier: AGPL-3.0-or-later
import { fileURLToPath } from "node:url";

export const APP_URL = process.env.APP_URL ?? "http://localhost:5173";
export const ADMIN_URL = process.env.ADMIN_URL ?? "http://localhost:5174";
// Hits the backend directly (bypassing each app's Vite dev proxy) for API-driven test setup.
export const API_URL = process.env.API_URL ?? "http://localhost:8000/api/v1";

// Where auth.setup.ts writes storageState files for specs to load via `test.use({ storageState })`.
// Gitignored (see e2e/.gitignore) - regenerated by the "setup" project on every run.
export const AUTH_DIR = fileURLToPath(new URL("../../.auth/", import.meta.url));
