"""Adding billing log, support for RevenueCat

Revision ID: 252558cdee48
Revises: e664cf2093fa
Create Date: 2026-10-04 15:35:57.293550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '252558cdee48'
down_revision: Union[str, Sequence[str], None] = 'e664cf2093fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('source', sa.Enum('gumroad', 'app_store', 'play_store', name='licence_source'), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'event_id', name='billing_events_source_event_id_key')
    )
    op.create_index(op.f('ix_billing_events_user_id'), 'billing_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('licence_source', sa.Enum('gumroad', 'app_store', 'play_store', name='licence_source'), nullable=True))
    op.add_column('users', sa.Column('app_store_subscription_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('perpetual_purchase_id', sa.Text(), nullable=True))
    op.execute("UPDATE users SET licence_source = 'gumroad' WHERE licence IN ('subscription', 'perpetual')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'perpetual_purchase_id')
    op.drop_column('users', 'app_store_subscription_id')
    op.drop_column('users', 'licence_source')
    op.drop_index(op.f('ix_billing_events_user_id'), table_name='billing_events')
    op.drop_table('billing_events')
    sa.Enum(name='licence_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
