"""add unique constraint on diary entries user id and entry date

Revision ID: 52e56b9f6e08
Revises: e2f183142cf6
Create Date: 2026-07-29 21:19:45.065548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52e56b9f6e08"
down_revision: Union[str, Sequence[str], None] = "e2f183142cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("diary_entries_user_id_entry_date_key", "diary_entries", ["user_id", "entry_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("diary_entries_user_id_entry_date_key", "diary_entries", type_="unique")
    # ### end Alembic commands ###
