"""Support Play Store id

Revision ID: d9be9c603036
Revises: 252558cdee48
Create Date: 2026-10-08 19:32:52.912383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

USER_TIER = postgresql.ENUM('fool', 'star', 'world', name='user_tier', create_type=False)
USER_TIER_SOURCE = postgresql.ENUM('default', 'billing', 'comp', name='user_tier_source', create_type=False)

# revision identifiers, used by Alembic.
revision: str = 'd9be9c603036'
down_revision: Union[str, Sequence[str], None] = '252558cdee48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('play_store_subscription_id', sa.Text(), nullable=True))
    op.drop_column('users', 'tier_cancels_at_period_end')  # migration-guard: allow
    op.drop_column('users', 'tier_expires_at')  # migration-guard: allow
    op.drop_column('users', 'tier_source')  # migration-guard: allow
    op.drop_column('users', 'tier')  # migration-guard: allow
    USER_TIER.drop(op.get_bind(), checkfirst=True)
    USER_TIER_SOURCE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    USER_TIER.create(op.get_bind(), checkfirst=True)
    USER_TIER_SOURCE.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('tier', USER_TIER,
                                     server_default=sa.text("'fool'::user_tier"), autoincrement=False, nullable=False))
    op.add_column('users',
                  sa.Column('tier_source', USER_TIER_SOURCE,
                            server_default=sa.text("'default'::user_tier_source"), autoincrement=False, nullable=False))
    op.add_column('users',
                  sa.Column('tier_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tier_cancels_at_period_end', sa.BOOLEAN(), server_default=sa.text('false'),
                                     autoincrement=False, nullable=False))
    op.drop_column('users', 'play_store_subscription_id')
    # ### end Alembic commands ###
